# Generated by Django 3.2.7 on 2021-10-14 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('activite', models.CharField(max_length=200)),
                ('niveau', models.CharField(max_length=200)),
                ('image', models.URLField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eps.categorie')),
            ],
        ),
    ]
